---
 
  - include_vars: vars/registrycrt.yml

  - name: enable ssh server in firewall
    ufw: rule=allow name=OpenSSH

  - name: enable docker in firewall
    ufw: rule=allow port=2375
  
  - name: start reload firewall
    ufw: state=enabled

  - name: add docker repo key
    apt_key: keyserver='hkp://p80.pool.sks-keyservers.net:80' id='58118E89F3A912897C070ADBF76221572C52609D'

  - name: add docker-engine apt repository
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

  - name: install docker engine {{ docker_engine_version }} 
    apt: name="docker-engine={{ docker_engine_version }}-0~trusty" state=installed update_cache=yes

  - name: update docker daemon configuration
    template: src=docker.j2 dest=/etc/default/docker
    notify: restart docker daemon

  - name: create directory for certificate
    file: state=directory path=/usr/local/share/ca-certificates/dev-docker-certs

  - name: copy registry private key
    copy:
      content: '{{ ssl_certificate }}'
      dest: /usr/local/share/ca-certificates/dev-docker-certs/devdockerCA.crt
      owner: root
      group: root
      mode: 0644
    notify: update ca certificates
  
  - meta: flush_handlers
